# Generated by Django 3.1.6 on 2021-02-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('type', models.CharField(choices=[('S', 'student'), ('T', 'teacher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('faculty_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('uc', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('type', models.CharField(choices=[('M', 'mandatory'), ('E', 'elective')], max_length=1)),
                ('hp', models.FloatField()),
                ('ht', models.FloatField()),
                ('school_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('deleted_date', models.DateField()),
                ('dni', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('enrollment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
